"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import Link from "next/link";

const features = [
  {
    title: "AI-Powered Examination",
    description:
      "Questions generated by NVIDIA NIM models that probe deep understanding of your codebase architecture and implementation details.",
    icon: (
      <svg className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9.663 17h4.673M12 3v1m6.364 1.636l-.707.707M21 12h-1M4 12H3m3.343-5.657l-.707-.707m2.828 9.9a5 5 0 117.072 0l-.548.547A3.374 3.374 0 0014 18.469V19a2 2 0 11-4 0v-.531c0-.895-.356-1.754-.988-2.386l-.548-.547z" />
      </svg>
    ),
  },
  {
    title: "Three Exam Modes",
    description:
      "Choose from Viva Voce, Interview Prep, or Code Review modes — each tailored to different assessment goals.",
    icon: (
      <svg className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 11H5m14 0a2 2 0 012 2v6a2 2 0 01-2 2H5a2 2 0 01-2-2v-6a2 2 0 012-2m14 0V9a2 2 0 00-2-2M5 11V9a2 2 0 012-2m0 0V5a2 2 0 012-2h6a2 2 0 012 2v2M7 7h10" />
      </svg>
    ),
  },
  {
    title: "Objective Scoring",
    description:
      "Nemotron-4-340B-Reward evaluates your answers on accuracy, depth, and awareness — harder to fool than standard LLMs.",
    icon: (
      <svg className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 01-2 2h-2a2 2 0 01-2-2z" />
      </svg>
    ),
  },
  {
    title: "Study Recommendations",
    description:
      "Get personalized study guides pointing to specific files, functions, and line numbers that need attention.",
    icon: (
      <svg className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 6.253v13m0-13C10.832 5.477 9.246 5 7.5 5S4.168 5.477 3 6.253v13C4.168 18.477 5.754 18 7.5 18s3.332.477 4.5 1.253m0-13C13.168 5.477 14.754 5 16.5 5c1.747 0 3.332.477 4.5 1.253v13C19.832 18.477 18.247 18 16.5 18c-1.746 0-3.332.477-4.5 1.253" />
      </svg>
    ),
  },
  {
    title: "Multi-Language Support",
    description:
      "Supports TypeScript, JavaScript, Python, Java, Go, Rust, and more — powered by Tree-sitter AST parsing.",
    icon: (
      <svg className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M10 20l4-16m4 4l4 4-4 4M6 16l-4-4 4-4" />
      </svg>
    ),
  },
  {
    title: "RAG-Grounded Questions",
    description:
      "Questions are grounded in your actual code using vector search and reranking — not generic programming questions.",
    icon: (
      <svg className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
      </svg>
    ),
  },
];

export default function LandingPage() {
  const router = useRouter();
  const [githubUrl, setGithubUrl] = useState("");
  const [isLoading, setIsLoading] = useState(false);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!githubUrl.trim()) return;

    setIsLoading(true);
    try {
      // For now, redirect to exam page with the URL
      router.push(`/exam?repo=${encodeURIComponent(githubUrl)}`);
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="min-h-screen">
      {/* Hero Section */}
      <section className="relative overflow-hidden bg-canvas-dark px-6 py-24 lg:py-32">
        <div className="mx-auto max-w-4xl text-center">
          <h1 className="text-4xl font-bold tracking-tight text-on-dark sm:text-5xl lg:text-6xl">
            Understand Your Code
            <span className="block text-primary">Deeply</span>
          </h1>
          <p className="mx-auto mt-6 max-w-2xl text-lg text-muted">
            AI-powered codebase examiner for viva preparation, project review,
            and interview readiness. Test your understanding with questions
            grounded in your actual code.
          </p>

          {/* GitHub URL Input */}
          <form onSubmit={handleSubmit} className="mt-10">
            <div className="mx-auto flex max-w-md flex-col gap-3 sm:flex-row">
              <Input
                variant="dark"
                placeholder="https://github.com/owner/repo"
                value={githubUrl}
                onChange={(e) => setGithubUrl(e.target.value)}
                className="flex-1"
                icon={
                  <svg className="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M10 6H6a2 2 0 00-2 2v10a2 2 0 002 2h10a2 2 0 002-2v-4M14 4h6m0 0v6m0-6L10 14" />
                  </svg>
                }
              />
              <Button
                type="submit"
                variant="primary"
                size="lg"
                disabled={!githubUrl.trim()}
                isLoading={isLoading}
              >
                Start Exam
              </Button>
            </div>
          </form>

          <p className="mt-4 text-sm text-muted">
            Paste a GitHub repository URL to begin
          </p>
        </div>
      </section>

      {/* Stats Section */}
      <section className="border-y border-hairline bg-surface px-6 py-12">
        <div className="mx-auto grid max-w-5xl grid-cols-2 gap-8 lg:grid-cols-4">
          <div className="text-center">
            <p className="text-3xl font-bold text-primary">5</p>
            <p className="mt-1 text-sm text-muted">NIM Models</p>
          </div>
          <div className="text-center">
            <p className="text-3xl font-bold text-primary">3</p>
            <p className="mt-1 text-sm text-muted">Exam Modes</p>
          </div>
          <div className="text-center">
            <p className="text-3xl font-bold text-primary">10+</p>
            <p className="mt-1 text-sm text-muted">Languages</p>
          </div>
          <div className="text-center">
            <p className="text-3xl font-bold text-primary">3</p>
            <p className="mt-1 text-sm text-muted">Score Dimensions</p>
          </div>
        </div>
      </section>

      {/* Features Section */}
      <section className="bg-canvas-dark px-6 py-24">
        <div className="mx-auto max-w-6xl">
          <div className="text-center">
            <h2 className="text-3xl font-bold text-on-dark">How It Works</h2>
            <p className="mt-3 text-muted">
              Powered by NVIDIA NIM for genuine code comprehension
            </p>
          </div>
          <div className="mt-16 grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-3">
            {features.map((feature, i) => (
              <Card key={i} variant="dark" className="border border-hairline">
                <CardContent className="p-6">
                  <div className="mb-4 flex h-12 w-12 items-center justify-center rounded-lg bg-primary/10 text-primary">
                    {feature.icon}
                  </div>
                  <h3 className="text-lg font-semibold text-on-dark">
                    {feature.title}
                  </h3>
                  <p className="mt-2 text-sm text-muted">
                    {feature.description}
                  </p>
                </CardContent>
              </Card>
            ))}
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="border-t border-hairline bg-surface px-6 py-24">
        <div className="mx-auto max-w-3xl text-center">
          <h2 className="text-3xl font-bold text-on-dark">
            Ready to Test Your Knowledge?
          </h2>
          <p className="mt-4 text-muted">
            Connect a repository and see how well you truly understand your code.
          </p>
          <div className="mt-8 flex justify-center gap-4">
            <Link href="/exam">
              <Button variant="primary" size="lg">
                Get Started
              </Button>
            </Link>
            <Link href="/repositories">
              <Button variant="secondary-dark" size="lg">
                View Repositories
              </Button>
            </Link>
          </div>
        </div>
      </section>
    </div>
  );
}
